### ISSUE TITLE
Remove name

### ISSUE THREAD

**Issue by ghost** [EngoEngine/math#1]
I give you the code on condition that you reupload the code, rewriting the git history to remove any trace of my name

**Comment by paked** [comment]
Is that even allowed by the LICENSE?

Either way, I think I'm going to remove this as a dependency.

**Comment by ghost** [comment]
You can remove/change the license if you want (and yeah it's my code, for now, so I can do that)

Either way you do can what you want as long as my name doesn't appear anywhere

**Comment by ghost** [comment]
```
cd $GOPATH/src/github.com/engoengine/math
rm -rf .git
git init
git add .
git commit -m "Initial commit"
git remote add origin git@github.com:engoengine/math.git
git push -u --force origin master
```

script to help (unix machines)

**Comment by paked** [comment]
@hydroflame Done. Would you like me to do the same to [`EngoEngine/glm`](https://github.com/EngoEngine/glm)?

Good luck with whatever you choose to do in the future.

**Comment by ghost** [comment]
yup
